---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: scg-routing-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: scg-routing-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: service-a
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: scg-routing-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: service-b
